spring:
  application:
    name: xp-user-server
  datasource:
    url: jdbc:mysql://tx-001:3306/x-peas?useUnicode=true&characterEncoding=utf-8&useSSL=false
    username: root
    password: Lijinquan9900
    driver-class-name: com.mysql.jdbc.Driver
  jpa:
    show-sql: true
    properties:
      hibernate:
        format_sql: true
        hbm2ddl.auto: update

eureka:
  client:
    service-url:
       defaultZone: http://localhost:8761/eureka/
  instance:
    instance-id: ${spring.application.name}.${server.port}
    prefer-ip-address: true

info:
  application.name: ${spring.application.name}
  version: ${project.version}
  coder:
    name: Lijq
    email: ly_0199@163.com