spring:
  application:
    name: xp-portal

server:
  port: 80

# zuul.routes.${app-name} = /${app-url-prefix}/**
zuul:
  ignored-services: "*"
  host:
    connect-timeout-millis: 10000
    socket-timeout-millis: 60000
  routes:
    xp-user-provider:
      path: /api/**
      serviceId: xp-user-provider


hystrix.command.default.execution.isolation.thread.timeoutInMilliseconds: 60000
ribbon:
  ConnectTimeout: 3000
  ReadTimeout: 60000