spring:
  application:
    name: xp-portal
server:
  port: 80

info:
  application.name: ${spring.application.name}
  version: 1.0-SNAPSHOT
  coder:
    name: Lijq
    email: ly_0199@163.com

eureka:
  client:
    service-url:
       defaultZone: http://localhost:8761/eureka/
#  instance:
#    instance-id: xp-portal
#    prefer-ip-address: true

# zuul
zuul:
  ignored-services: "*"
  routes:
    user:
      path: /api/user/**
      serviceId: xp-user-provider





