spring:
  application:
    name: xp-cloud-eureka-server
#  security:
#    user:
#      name: root
#      password: root

server:
  port: 8761

eureka:
  server:
    enable-self-preservation: false
    #eviction-interval-timer-in-ms: 5000
  instance:
    hostname: localhost
  client:
    # 取消自我注册
    register-with-eureka: false
    # 不需要检索服务
    fetch-registry: false
    # 服务URL
    service-url:
      defaultZone: http://${eureka.instance.hostname}:${server.port}/eureka


